// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdfwlTQXwYiChJ-1MrAEmyx4Zx4hv93I8',
    appId: '1:181111609166:web:e12ded87479d2bbfa2f01f',
    messagingSenderId: '181111609166',
    projectId: 'todo-3ff45',
    authDomain: 'todo-3ff45.firebaseapp.com',
    storageBucket: 'todo-3ff45.firebasestorage.app',
    measurementId: 'G-YJC9ZQRVWQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy5kxmxpkKUfCFnf_Gu91ivLLtn9KLG94',
    appId: '1:181111609166:android:e1880d6b8e4baf50a2f01f',
    messagingSenderId: '181111609166',
    projectId: 'todo-3ff45',
    storageBucket: 'todo-3ff45.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfVwZW07_V5gnws3vAYg4fjX9E-HKhp7I',
    appId: '1:181111609166:ios:0033d13f69426002a2f01f',
    messagingSenderId: '181111609166',
    projectId: 'todo-3ff45',
    storageBucket: 'todo-3ff45.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfVwZW07_V5gnws3vAYg4fjX9E-HKhp7I',
    appId: '1:181111609166:ios:0033d13f69426002a2f01f',
    messagingSenderId: '181111609166',
    projectId: 'todo-3ff45',
    storageBucket: 'todo-3ff45.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdfwlTQXwYiChJ-1MrAEmyx4Zx4hv93I8',
    appId: '1:181111609166:web:7aa8d69a4dae34b6a2f01f',
    messagingSenderId: '181111609166',
    projectId: 'todo-3ff45',
    authDomain: 'todo-3ff45.firebaseapp.com',
    storageBucket: 'todo-3ff45.firebasestorage.app',
    measurementId: 'G-3SMSBDRHW7',
  );
}
